### ISSUE TITLE
Add DSTU2 Support

### ISSUE THREAD

**Issue by RockHoward** [nazrulworld/fhir.resources#1]
* fhir.resources version: DSTU2
* Python version: 2.7
* Operating System: *nix

### Description

I am supporting several FHIR projects and I need support for DSTU2 and well as STU3 and R4.

### What I Did

I looked at the code and discovered that code supporting STU3 was included, but not DSTU2.

**Comment by nazrulworld** [comment]
I was trying to add DSTU2 support but normally not possible by generator (as it is for latest FHIR specification). However I will try other soon if i can manage time.

**Comment by nazrulworld** [comment]
@RockHoward  Please check new release! https://pypi.org/project/fhir.resources/5.0.0b3/

**Comment by RockHoward** [comment]
Brilliant. I will start testing DSTU2 right away!
