### ISSUE TITLE
Transition to R5

### ISSUE THREAD

**Issue by alysivji** [nazrulworld/fhir.resources#126]
FHIR R5 was released -- it is now the default version for the [documentation pages on HL7.org](https://www.hl7.org/fhir/medicationstatement.html).

This library has R4 has the default. What's the transition plan for moving to R5? What can I do to ensure my project uses R4 until I'm ready to switch to R5?

Thanks!

**Comment by wowkin2** [comment]
Also curious.
Here is the diff between 4 and 5: http://hl7.org/fhir/5.0.0-draft-final/diff.html#r4r5

**Comment by wowkin2** [comment]
Found previous discussion in [README.rst](https://github.com/nazrulworld/fhir.resources#fhir-release-r4b-over-r4):
> FHIR release R4B is coming with not that much changes over the release of R4. So we decided not to create separate sub-package for R4 like STU3, instead there just overlaps on existing R4. This also means that in future, when we will work on R5; there will be sub-package for R4B and no R4. We suggest you to try make a plan to be upgraded to R4B. Here you could find related information [dealing-strategy-R4-R4B](https://confluence.hl7.org/display/FHIR/Strategies+for+dealing+with+R4+and+R4B).
> 
> You could find full discussion here https://github.com/nazrulworld/fhir.resources/discussions/116
