### ISSUE TITLE
`pkg_resources.declare_namespace` deprecation

### ISSUE THREAD

**Issue by azmeuk** [nazrulworld/fhir.resources#128]
* fhir.resources version: 7.0.0
* Python version: 3.11
* Operating System: archlinux

When running unit tests on my application that uses fhir.resources, I get this warning message:

```python
  /path/to/lib/python3.11/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('fhir')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
```

The culprit seems to be this line:

https://github.com/nazrulworld/fhir.resources/blob/02b04257dfe2f956fb2c7825624da50f8a464afd/fhir/__init__.py#L1

**Comment by nazrulworld** [comment]
Thanks
