### ISSUE TITLE
Restrict Pydantic to <2.0.0

### ISSUE THREAD

**Issue by anmolmittal1** [nazrulworld/fhir.resources#134]
* fhir.resources version: 7.0.2
* Python version: 3.7
* Operating System: Debian 10

### Description

Latest version errors out as it is trying to install pydantic v2 which includes some breaking changes.
https://github.com/nazrulworld/fhir.resources/blob/main/setup.py#L20 - min version is restricted but please add max version cap to <2.0.0 as well

### What I Did
Relevant traceback
```
/usr/local/lib/python3.7/dist-packages/helix_personmatching/matchers/matcher.py:5: in <module>
    from fhir.resources.bundle import Bundle
/usr/local/lib/python3.7/dist-packages/ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
/usr/local/lib/python3.7/dist-packages/fhir/resources/__init__.py:5: in <module>
    from fhir.resources.core.fhirabstractmodel import FHIRAbstractModel
/usr/local/lib/python3.7/dist-packages/ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
/usr/local/lib/python3.7/dist-packages/fhir/resources/core/fhirabstractmodel.py:13: in <module>
    from pydantic.class_validators import ROOT_VALIDATOR_CONFIG_KEY, root_validator
E   ImportError: cannot import name 'ROOT_VALIDATOR_CONFIG_KEY' from 'pydantic.class_validators' (/usr/local/lib/python3.7/dist-packages/pydantic/class_validators.py)
```

**Comment by nazrulworld** [comment]
Relevant issue is https://github.com/nazrulworld/fhir.resources/issues/133 | I think we should move with Pydantic v2.X. For unfortunately you have to self restrict lower version pydantic for now.

**Comment by anmolmittal1** [comment]
@nazrulworld I have restricted the pydantic version manually for my use case currently.
I also agree with the move to Pydantic v2 as it brings in a lot of performance improvements but created this issue as the package would be breaking for a lot of users who have not locked their pydantic version. Hopefully we can get a quick minor/patch release with pydantic v1 cap for now!

**Comment by nazrulworld** [comment]
https://pypi.org/project/fhir.resources/7.0.2/
