### ISSUE TITLE
Resource / element to be json-serializable

### ISSUE THREAD

**Issue by vadi2** [nazrulworld/fhir.resources#146]
* fhir.resources version: 7.0.2
* Python version: 3.9.2
* Operating System: Debian

### Description

How can I make a resource or an element be easily serializable? I'm populating a non-FHIR dictionary with FHIR elements and I'd like to then `json.dump` it. 

### What I Did

At the moment I'm doing `json.loads(element.json())` to make it easily serializable, but that's not very efficient.

**Comment by nazrulworld** [comment]
@vadi2 did you tried `element.dict()`?

**Comment by vadi2** [comment]
That was it. Thanks!
