### ISSUE TITLE
fhir.resource 8.0.0b1 beta feedback

### ISSUE THREAD

**Issue by janwijbrand** [nazrulworld/fhir.resources#164]
* fhir.resources version: 8.0.0b1
* Python version: 3.11
* Operating System: MacOS Sonoma

#### fhir.resource 8.0.0b1 beta feedback.

The reason for the 8.0.0b1 release is to collect feedback. Since I couldn't find the place where that feedback currently is collected, I start this issue. I hope that this is helpful to you:

1. no more `Resource.resource` attribute. Now use `Resource.get_resource_type()` instead? If this is intentional it should be listed in the migration guide from 7.x -> 8.x. However, I'd argue the `resource_type` attribute is more intuitive and also more closely resembles the JSON you get from a FHIR server.
2. `get_fhir_model_class()` is gone? I use it in a central location of my codebase where I abstract out the requests to a FHIR server and return a resource object. If this function is intentionally gone, it should be listed in the migration guide from 7.x --> 8.x. However, I hope this function comes back or has a proper alternative.

Please let me know if I can help address those issues in any way, or test upcoming betas.

**Comment by janwijbrand** [comment]
More beta-testing feedback:

In `fhir.resources == 7.1.0`:

```
❯ python3.11 -m venv fhir.resources-7
❯ cd fhir.resources-7
❯ ./bin/pip install fhir.resources==7.1.0
❯ ./bin/python
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fhir.resources.R4B.task import Task
>>> t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})
>>> t1.dict(exclude_none=True)
OrderedDict([('resourceType', 'Task'), ('status', 'active'), ('intent', 'plan')])
>>>
```

contrast that to `fhir.resources == 8.0.0b1`:

```
❯ python3.11 -m venv fhir.resources-8
❯ cd fhir.resources-8/
❯ ./bin/pip install fhir.resources=8.0.0b1
❯ ./bin/python
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fhir.resources.R4B.task import Task
>>> t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/j.kolman/tmp/fhir.resources-8/lib/python3.11/site-packages/fhir_core/fhirabstractmodel.py", line 96, in __init__
    BaseModel.__init__(self, **data)
  File "/Users/j.kolman/tmp/fhir.resources-8/lib/python3.11/site-packages/pydantic/main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/j.kolman/tmp/fhir.resources-8/lib/python3.11/site-packages/fhir_core/types.py", line 161, in _validate
    return validator(cls.fhir_model_validator(input_value, model_klass))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/j.kolman/tmp/fhir.resources-8/lib/python3.11/site-packages/fhir_core/types.py", line 202, in fhir_model_validator
    if model_klass.__resource_type__ != value.__resource_type__:
                                        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__resource_type__'
>>>
```

Is this difference in behaviour intentional? This could lead to problems perhaps, when deserializing JSON or a Python dict from some unknown source that has a null or None value for the `for` field. 

Please let me know if I can help address those issues in any way, or test upcoming betas.

**Comment by nazrulworld** [comment]
@janwijbrand thanks a lot for your feedback. 
I think, we can use this thread to collect others feedback.

**Comment by ynarwal** [comment]
Hi @nazrulworld , thanks for your efforts in migrating to Pydantic 2! Although it's still in beta, we're planning to use version `8.0.0b1` in our project, specifically for parsing FHIR payloads, and it's been working well for us. Do you have any rough timeline in mind for when this might be promoted to an official release?

**Comment by nazrulworld** [comment]
@ynarwal nice to hear that you can run your system without problem. I think that we will do a stable release soon, but I can see yet to have to work for xml and yaml serialization/deserialization

**Comment by nazrulworld** [comment]
@janwijbrand "missing and the "attribute error for resource type on None" issues need to be resolved", I fully agree with that. About `get_fhir_model_class() ` I will look on this soon (but I also not have that time) and make a new beta release

**Comment by nazrulworld** [comment]
@janwijbrand you can have a look at the new release https://pypi.org/project/fhir.resources/8.0.0b2/

**Comment by janwijbrand** [comment]
Thanks @nazrulworld! I'll try to look at this week!

**Comment by ynarwal** [comment]
@janwijbrand FYI it worked for me 

```python

from fhir.resources.R4B.task import Task

t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})

print(t1.get_resource_type())

```

```
>  python test_fhir_package.py
Task
```

**Comment by janwijbrand** [comment]
Great to have `get_fhir_model_class()` back!

**Comment by janwijbrand** [comment]
> @janwijbrand FYI it worked for me in `8.0.0b2`
> 
> ```python
> from fhir.resources.R4B.task import Task
> 
> t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})
> 
> print(t1.get_resource_type())
> ```
> 
> ```
> >  python test_fhir_package.py
> Task
> ```

👍 I'll test it indeed.

**Comment by janwijbrand** [comment]
@ynarwal @nazrulworld Indeed for the `Task`-case it works. Strangely enough, not for another type of resource that I tried:

```
>>> from fhir.resources.R4B.task import Task
>>> t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})
>>> t1.for_fhir is None
True
>>> t1.intent
'plan'
>>>
>>> from fhir.resources.R4B.activitydefinition import ActivityDefinition
>>> ad1 = ActivityDefinition(**{'status': 'active', 'subtitle': None})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/j.kolman/.buildout/eggs/cp311/fhir_core-0.1.0b9-py3.11.egg/fhir_core/fhirabstractmodel.py", line 96, in __init__
    BaseModel.__init__(self, **data)
  File "/Users/j.kolman/.buildout/eggs/cp311/pydantic-2.9.2-py3.11.egg/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ActivityDefinition
subtitle
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
```

For my use-case this is still a blocking issue; I create those resources programmatically, translation domain specific objects into FHIR resources. Do you need more insights into how I do that to see if I'm abusing `fhir.resources` and there's other, better ways to accomplish what I need?

**Comment by ynarwal** [comment]
> @ynarwal @nazrulworld Indeed for the `Task`-case it works. Strangely enough, not for another type of resource that I tried:
> 
> ```
> >>> from fhir.resources.R4B.task import Task
> >>> t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})
> >>> t1.for_fhir is None
> True
> >>> t1.intent
> 'plan'
> >>>
> >>> from fhir.resources.R4B.activitydefinition import ActivityDefinition
> >>> ad1 = ActivityDefinition(**{'status': 'active', 'subtitle': None})
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/Users/j.kolman/.buildout/eggs/cp311/fhir_core-0.1.0b9-py3.11.egg/fhir_core/fhirabstractmodel.py", line 96, in __init__
>     BaseModel.__init__(self, **data)
>   File "/Users/j.kolman/.buildout/eggs/cp311/pydantic-2.9.2-py3.11.egg/pydantic/main.py", line 212, in __init__
>     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> pydantic_core._pydantic_core.ValidationError: 1 validation error for ActivityDefinition
> subtitle
>   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
>     For further information visit https://errors.pydantic.dev/2.9/v/string_type
> ```


@janwijbrand, isn't this behavior expected? The `subtitle` field is optional, so if it's not provided, everything works fine. However, when it is specified, it must be a valid string. If `subtitle` has no value, omitting it works as intended. I believe this is more of a Pydantic behavior rather than an issue with `fhir.resources`.

**Comment by janwijbrand** [comment]
Perhaps it is Pydantic behaviour, but if it is, it is new in Pydantic v2? In my fhir.resource 7.x/Pydantic v1 based code all works like above. Let me try to illustrate what I do in my codebase:

```
from fhir.resources.R4B.activitydefinition import ActivityDefinition
from fhir.resources.R4B.identifier import Identifier

def activitydefinition_for_content(
    base_url: str, 
    content: Content
) -> ActivityDefinition:
    title = content.title
    activitydefinition = ActivityDefinition(
        identifier=[
            Identifier(
                system='https://example.org/some-ns/identifiers',
                value=content.id,
                use='official',
            )
        ],
        description=content.description,
        name=content.id,
        status='active' if content.activated else 'retired',
        subtitle=content.subtitle,
        title=title,
        topic=['treatment'],
        url=f'{base_url}/catalogue/{content.id}',
        version=str(content.current_version),
    )
    return activitydefinition
```

You see, here I adapt the domain specific "Content" object into a FHIR resource. The `subtitle` of the domain object is optional: so it is `None` or a `str`. The code would look very ugly if I would need to "know" for each field if I can pass in `None` (like for `Task.for` it is possible) or if I need to conditionally set like so:

```
def activitydefinition_for_content(
    base_url: str, 
    content: Content
) -> ActivityDefinition:
    title = content.title
    activitydefinition = ActivityDefinition(
        identifier=[
            Identifier(
                system='https://example.org/some-ns/identifiers',
                value=content.id,
                use='official',
            )
        ],
        description=content.description,
        name=content.id,
        status='active' if content.activated else 'retired',
        title=title,
        topic=['treatment'],
        url=f'{base_url}/catalogue/{content.id}',
        version=str(content.current_version),
    )
    if content.subtitle is not None:
        activitydefinition.subtitle = content.subtitle
    return activitydefinition
```

And this would be an easy case...

Also, I wonder why then for `Task.for` a value of `None` _is_ acceptable?

IOW, if this really boils down to Pydantic v2 behaviour, I dislike Pydantic v2 even more (I had to fight URL fields no longer being strings big time as well).

Any opinions or suggestions highly appreciated!

**Comment by nazrulworld** [comment]
> @ynarwal @nazrulworld Indeed for the `Task`-case it works. Strangely enough, not for another type of resource that I tried:
> 
> ```
> >>> from fhir.resources.R4B.task import Task
> >>> t1 = Task(**{'for': None, 'intent': 'plan', 'status': 'active'})
> >>> t1.for_fhir is None
> True
> >>> t1.intent
> 'plan'
> >>>
> >>> from fhir.resources.R4B.activitydefinition import ActivityDefinition
> >>> ad1 = ActivityDefinition(**{'status': 'active', 'subtitle': None})
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/Users/j.kolman/.buildout/eggs/cp311/fhir_core-0.1.0b9-py3.11.egg/fhir_core/fhirabstractmodel.py", line 96, in __init__
>     BaseModel.__init__(self, **data)
>   File "/Users/j.kolman/.buildout/eggs/cp311/pydantic-2.9.2-py3.11.egg/pydantic/main.py", line 212, in __init__
>     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> pydantic_core._pydantic_core.ValidationError: 1 validation error for ActivityDefinition
> subtitle
>   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
>     For further information visit https://errors.pydantic.dev/2.9/v/string_type
> ```
> 
> For my use-case this is still a blocking issue; I create those resources programmatically, "adapting" domain specific objects into FHIR resources. Do you need more insights into how I do that to see if I'm abusing `fhir.resources` and there's other, better ways to accomplish what I need?

I think that is a real issue, that should have a creative solution. But in the meanwhile, you could follow @ynarwal 's solution (avoid None value)

**Comment by ynarwal** [comment]
@nazrulworld @janwijbrand We need to make model fields optional as per fhir standard.
For example `AcitivityDefinition.subtitle` is optional in fhir spec but it's not in our model.
please see [here](https://github.com/nazrulworld/fhir.resources/blob/pydantic-v2-experimental/fhir/resources/R4B/activitydefinition.py#L686-L697)

If I make this optional then it works

```py
    # from typing import Optional

  subtitle: Optional[fhirtypes.StringType] = Field(  # type: ignore
      None,
      alias="subtitle",
      title="Subordinate title of the activity definition",
      description=(
          "An explanatory or alternate title for the activity definition giving "
          "additional information about its content."
      ),
      json_schema_extra={
          "element_property": True,
      },
  )
```

```py
>>> from fhir.resources.R4B.activitydefinition import ActivityDefinition
>>> ad1 = ActivityDefinition(**{'status': 'active', 'subtitle': None})
```

This field is just an example. We have to mark a lot of fields optional.

**Comment by janwijbrand** [comment]
I had the impression, the model code is generated from the FHIR profiles right? Or is it done by hand? So, instead of marking individual fields of inidiviudal resource models as optional, it needs a change in the FHIR-profile-parser-code-generator?

**Comment by nazrulworld** [comment]
> @nazrulworld @janwijbrand We need to make model fields optional as per fhir standard. For example `AcitivityDefinition.subtitle` is optional in fhir spec but it's not in our model. please see [here](https://github.com/nazrulworld/fhir.resources/blob/pydantic-v2-experimental/fhir/resources/R4B/activitydefinition.py#L686-L697)
> 
> If I make this optional then it works
> 
> ```python
>     # from typing import Optional
> 
>   subtitle: Optional[fhirtypes.StringType] = Field(  # type: ignore
>       None,
>       alias="subtitle",
>       title="Subordinate title of the activity definition",
>       description=(
>           "An explanatory or alternate title for the activity definition giving "
>           "additional information about its content."
>       ),
>       json_schema_extra={
>           "element_property": True,
>       },
>   )
> ```
> 
>  ```python
> >>> from fhir.resources.R4B.activitydefinition import ActivityDefinition
> >>> ad1 = ActivityDefinition(**{'status': 'active', 'subtitle': None})
> ```
> 
> This field is just an example. We have to mark a lot of fields optional. @nazrulworld Am I correct to say this?

That's a nice catch! I will look on it soon. As far as I knew in pydantic v1, default=None makes field optional but here I can see pydantic v2 behaviour is different.

**Comment by nazrulworld** [comment]
> I had the impression, the model code is generated from the FHIR profiles right? Or is it done by hand? So, instead of marking individual fields of inidiviudal resource models as optional, it needs a change in the FHIR-profile-parser-code-generator?

yes, you are right, provably , we have to re-generate!

**Comment by janwijbrand** [comment]
(Thanks @nazrulworld and @ynarwal for the follow ups, it is appreciated)

**Comment by nazrulworld** [comment]
Checkout the new release https://pypi.org/project/fhir.resources/8.0.0b3/

**Comment by janwijbrand** [comment]
I'm not done testing, but the beta 3 is promising! I'll continue testing and report back a little later.

There's one _really annoying_ problem (IMHO) with Pydantic V2 and that is its URL handling. URLs in Pydantic are no longer strings, and there's implicit behaviour with adding trailing slashes in certain situations.

I would argue that Pydantic V2's behaviour is not what we should want for `fhir.resources` as it could implicitly change the values for URL properties from incoming data.

One example is, that `Endpoint.address` is a URL and not a str anymore and you can no longer pass it on to your http client library without "decoding" it into a string. I have many places in my code base where I run into this situation and it is really irritating.

See for reference and other discussion and alternatives:

https://github.com/pydantic/pydantic/issues/7186
https://github.com/pydantic/pydantic/issues/9176

Perhaps we can consider using something like this:

https://pypi.org/project/pydantic-string-url/

What's your opinion? It is making my life very difficult at the moment.

**Comment by apollo13** [comment]
I have done some testing as well and it is mostly good. What did change though is the errors. In FHIR < 8 I got `value_error.missing` if an input didn't have the required field set. In FHIR 8 I do get `model_field_validation_format`:
https://github.com/nazrulworld/fhir-core/blob/c79c958509f7e861e29f4c4e26c6f8aa39aaa389/fhir_core/fhirabstractmodel.py#L561-L565

It would be great to follow pydantic here and have  "missing" as a type. If that is not possible maybe do something like `model_field_validation.missing` so end user code can properly detect this.

**Comment by nazrulworld** [comment]
@apollo13 thanks a lot for your input.
Checkout the latest release https://pypi.org/project/fhir.resources/8.0.0b4/

**Comment by apollo13** [comment]
Thank you @nazrulworld, that looks way better. Will report if I find anything else.

**Comment by nazrulworld** [comment]
@janwijbrand you are always welcome to make PR!

**Comment by ynarwal** [comment]
Hello all. Just want to touch base on the plan for v8 release.

Are we waiting @janwijbrand's PR before we do a public v8 release?

**Comment by janwijbrand** [comment]
> Hello all. Just want to touch base on the plan for v8 release.
> Are we waiting @janwijbrand's PR before we do a public v8 release?

Ah, good point. So, all in all you would see practical value in changing from the non-`str` URL fields in Pydantic V2 to a `str`-compatible variant?

If that's the case I could try to carve out some (work) time this week or in the third week of December. 

Thanks for asking!

**Comment by janwijbrand** [comment]
I'll try to find some time today (perhaps Monday) to test this with my application that depdends on `fhir.resources` and URL-as-string behaviour.

**Comment by nazrulworld** [comment]
@janwijbrand thanks a lot for your great effort. As soon as fhir-core & fhir.resources tests coverage is OK (travis), I have happy :).

I am thinking  about extra package dependency for fhir-core. Can we avoid that dependency some how?  Or what about Pydantic it-self, will they come with a solution (in that case we can create a patch, until new release)

**Comment by apollo13** [comment]
> There's one really annoying problem (IMHO) with Pydantic V2 and that is its URL handling. URLs in Pydantic are no longer strings, and there's implicit behaviour with adding trailing slashes in certain situations.

I agree that adding trailing slashes might be problematic (even though if done right I think it generally should be okayish -- but out of an abundance of caution I would recommend against it currently). As for the extra type I think this would actually be okay (even if you cannot pass it as is to http clients). Personally I haven't run into issues yet but we don't really use URLs in a way where it concerns us yet. I'd be fine with either solution though I'd slightly prefer a URL object over strings.

**Comment by janwijbrand** [comment]
> @janwijbrand thanks a lot for your great effort. As soon as fhir-core & fhir.resources tests coverage is OK (travis), I have happy :).
> 
> I am thinking about extra package dependency for fhir-core. Can we avoid that dependency some how? Or what about Pydantic it-self, will they come with a solution (in that case we can create a patch, until new release)

Pydantic seems to be all on board with this behavioural change that URLs are no longer strings. I don't expect that to change.

The only way to not have the extra dep is inline that URL-subclasses-string code. Would you prefer that?

I would still like your _explicit_ approval/opinion that you want `fhir.resources`'s URLs to subclass string. You will be diverging from Pydantic's choice that way. Personally _I_ find Pydantic's choice strange, but I want to make clear we need to explain this is in the `fhir.resources` docs.

**Comment by janwijbrand** [comment]
> I'd be fine with either solution though I'd slightly prefer a URL object over strings.

This is interesting. Can you explain why you slightly prefer it? Are you fine with then having to coerce URLs that come out of the FHIR resources you fetch to `str` whenever you pass it on to, say, a HTTP library? (httpx or requests or whatever).

**Comment by nazrulworld** [comment]
> >  The only way to not have the extra dep is inline that URL-subclasses-string code. Would you prefer that?

That could be good idea, let's try that 👍

**Comment by apollo13** [comment]
> This is interesting. Can you explain why you slightly prefer it? 

I like to see `fhir.resources` as a lightweight wrapper around pydantic providing some extra functionality. So in that sense I would follow pydantics lead unless there is a good reason not to. Also an URL-object can be seen as providing clear semantics which a string cannot easily transport leading to issues down the road. Take for instance the following (maybe even user-supplied) URL as an example: `https://example.com/I-like-this-a-100%-and-would-do-it-again`. Would you say this URL is properly percent-encoded? Having an URL-object also allows me to easily ask it for the host etc without having to parse it over an over again (see below on why you probably want to know that).

> Are you fine with then having to coerce URLs that come out of the FHIR resources you fetch to `str` whenever you pass it on to, say, a HTTP library? (httpx or requests or whatever).

Since I usually have wrapper functions around external calls I would have to do it in one location which is really a none-issue. This wrapper does many things usually needed in larger systems:

 * Implement timeout & retry handling as required by the project.
 * In web-projects doing redirects: Check if the host that is being redirected to is "safe", essentially this means that the target host is on the "same" domain. So a login with redirect ala `https://good.com/login?redirect_after_login=https://evil.com` does not work.
 * Resolve the host to check if the target is "safe", ie not in the internal network. Take webhooks as an example. If a user adds a webhook to your system you really don't want them to allow webhooks to `http://localhost:1234` or `http://some.internal.service`.

**Comment by Tshimanga** [comment]
@nazrulworld Hey! Sorry I've been preoccupied a while with work. Just found a little bit of time to play with the new 8.x release and stumbled upon the following

```
DocumentReferenceContext(encounter=Reference(reference="Encounter/1"))
AttributeError: 'tuple' object has no attribute '__resource_type__'
```

I was using the `8.0.0b4` release.

**Comment by janwijbrand** [comment]
> > This is interesting. Can you explain why you slightly prefer it?
> 
> I like to see `fhir.resources` as a lightweight wrapper around pydantic providing some extra functionality. <snip>
> 
> > Are you fine with then having to coerce URLs that come out of the FHIR resources you fetch to `str` whenever you pass it on to, say, a HTTP library? (httpx or requests or whatever).
> 
> Since I usually have wrapper functions around external calls I would have to do it in one location which is really a none-issue. <snip>

Both reasonable points. 

And, the more i think I about the more I feel "we" (a.k.a. I) should resist the urge to try and swim against the Pydantic-current here. Diverging now might become a maintenance burden later and maybe even more difficult to explain for "newcomers that do know Pydantic". I still don't like it, but well, what can you do :)

I'm going to close the PR @nazrulworld and continue testing with fhir.resources as-is, even if that means making a few more changes to my app. It was a nice learning experience anyway. Thanks for the feedback!

**Comment by janwijbrand** [comment]
I guess we can still keep _this_ discussion open as it is about beta release feedback in general?

**Comment by nazrulworld** [comment]
> I guess we can still keep _this_ discussion open as it is about beta release feedback in general?

Yes, I think that would be good idea to keep open, until there is a full release. @Tshimanga already has found a bug that I will look on as soon as possible.

**Comment by nazrulworld** [comment]
> DocumentReferenceContext(encounter=Reference(reference="Encounter/1"))

I can see it's not a bug, instead of the wrong value (type) has been provided. For example `encounter` value should be list of Reference. `DocumentReferenceContext(encounter=[Reference(reference="Encounter/1")])`

But the error message is confusing, we should look on it.

**Comment by Tshimanga** [comment]
@nazrulworld yep, I haven't had a chance to look into why the error message is the way it is but I can take a look this weekend if you haven't yet. By the way, it looks like physionet now provides the entirety of [MIMIC IV in FHIR format](https://physionet.org/content/mimic-iv-fhir/2.1/) as well now ^_^

**Comment by aschwtzr** [comment]
@nazrulworld first of all thank you for the excellent library! It's been really easy to implement and robust so far. F

HIRPatient below is a subclass of Patient which works like a charm, but I'm running into an issue with AppointmentParticipant  where the resourceType is being dropped during serialization

```
participant_json = {
    "actor": {
        "reference": f"Patient/{FHIRPatient.from_client(client).id}"
    },
    "status": "needs-action"
}

appt_participant = AppointmentParticipant(**participant_json)
pprint.pprint(appt_participant.dict()) 
# {'actor': {'reference': 'Patient/8956be76-c975-4e10-a701-5d05c9cbb127'}, 'status': 'needs-action'}

appt_json = {
    "participant": [appt_participant.dict()],
    "status": "proposed"
}

appt = Appointment(**appt_json)
pprint.pprint(appt.dict())
# {'participant': [{'actor': {'reference': 'Patient/8956be76-c975-4e10-a701-5d05c9cbb127'}, 'status': 'needs-action'}], 'resourceType': 'Appointment',  'status': 'proposed'}
```

Wondering if this is related to the migration and whether you could point me in the right direction to put in a patch.

**Comment by nazrulworld** [comment]
@aschwtzr  thanks a lot for your appreciation.  Is it possible to paste full codes (includes your subclasses ), so that I can test in my local.

**Comment by aschwtzr** [comment]
This is the gist of it which gives me a valid FHIR Appointment and nested AppointmentParticipant. Not sure if creating the participant first was the issue. 

One last thing we noticed is a few of these are still on the old `__resource_type__` property. Appointment off the top of my head but will run a small test later today and update the comment

```
class AlpacaClient(BaseModel):
    client_first_name: Optional[str] = None
    client_last_name: Optional[str] = None
    id: Optional[str] = Field(default=None, alias="_id")
    medplum_id: Optional[str] = None

class FHIRAppointmentParticipant(AppointmentParticipant):
    alpaca_id: Optional[str] = Field(default=None, exclude=True)
    medplum_id: Optional[str] = Field(default=None, exclude=True)
        
    @staticmethod
    def from_alpaca_client(alpaca_client: AlpacaClient):
        participant_json = {
            "actor": {
                "reference": f"Patient/{alpaca_client.medplum_id}",
                "display": f"{alpaca_client.client_first_name} {alpaca_client.client_last_name}"
            },
            "status": "needs-action",
            "required": "required"
        }
        return AppointmentParticipant(**participant_json)

class AlpacaAppointment(BaseModel):
    id: Optional[str] = Field(None, description="The logical id of the resource")
    resource_type: str = Field(default="Appointment")
    status: Literal[
        "proposed", "pending", "booked", "arrived", 
        "fulfilled", "cancelled", "noshow", "entered-in-error", 
        "checked-in", "waitlist"
    ] = Field(description="The overall status of the Appointment", default="proposed")
    participant: List[AlpacaClient] = Field(..., description="List of participants involved in the appointment")
    medplum_id: Optional[str] = Field(None, exclude=True, description="The Medplum ID of the resource.")

class FHIRAppointment(Appointment):
    medplum_id: Optional[str] = Field(None, exclude=True, description="The Medplum ID of the resource.")
    alpaca_id: Optional[str] = Field(None, exclude=True, description="The Alpaca ID of the resource.")
    
    @staticmethod
    def from_alpaca_appointment(alpaca_appointment: AlpacaAppointment):
        fhir_json = alpaca_appointment.model_dump(exclude_none=True)
        fhir_json["participant"] = [FHIRAppointmentParticipant.from_alpaca_client(participant) for participant in alpaca_appointment.participant]
        fhir_json["resourceType"] = "Appointment"
        return FHIRAppointment(**fhir_json)
```

**Comment by nazrulworld** [comment]
> @nazrulworld first of all thank you for the excellent library! It's been really easy to implement and robust so far.
> 
> FHIRPatient below is a subclass of Patient which works like a charm, but I'm running into an issue with AppointmentParticipant where the resourceType is being dropped during serialization
> 
> ```
> participant_json = {
>     "actor": {
>         "reference": f"Patient/{FHIRPatient.from_client(client).id}"
>     },
>     "status": "needs-action"
> }
> 
> appt_participant = AppointmentParticipant(**participant_json)
> pprint.pprint(appt_participant.dict()) 
> # {'actor': {'reference': 'Patient/8956be76-c975-4e10-a701-5d05c9cbb127'}, 'status': 'needs-action'}
> 
> appt_json = {
>     "participant": [appt_participant.dict()],
>     "status": "proposed"
> }
> 
> appt = Appointment(**appt_json)
> pprint.pprint(appt.dict())
> # {'participant': [{'actor': {'reference': 'Patient/8956be76-c975-4e10-a701-5d05c9cbb127'}, 'status': 'needs-action'}], 'resourceType': 'Appointment',  'status': 'proposed'}
> ```
> 
> Wondering whether this is related to the migration and if you could point me in the right direction to put in a patch. I have been digging through the repo but can't pinpoint where this is happening

I don't see any problem on serialization. AppointmentParticipant is not Resource Type, instead it's Backbone Element type.
 The `resourceType` field is existing only for any FHIR Resource, which is listed here https://www.hl7.org/fhir/resourcelist.html

You can see one example bellow:   
https://hapi.fhir.org/baseR4/Appointment/113885/_history/1

**Comment by nazrulworld** [comment]
This thread is closed based on the final release https://pypi.org/project/fhir.resources/8.0.0/
