### ISSUE TITLE
8.0.0 Difference in handling of base64Binary data

### ISSUE THREAD

**Issue by adamvonpaternos** [nazrulworld/fhir.resources#166]
* fhir.resources version: 8.0.0b4
* fhir-core==0.1.3
* Python version: 3.12.5
* Operating System: macOS

### Description

First off, thank you for all the hard work on the fhir.resources library. This tool has been incredibly helpful in streamlining FHIR resource creation, validation, and the flexibility is truly appreciated.

In the upcoming release of v8.0.0 I'm wondering if there is unintended behavior for elements with the base64Binary primitive type. There is a discrepancy with the passed arguments into model fields annotated with this type and the resulting constructed object. The byte object now uses the Pydantic Base64Encoder which encodes the data upon construction and subsequently decodes upon serialization. This differs with how these elements were handled in fhir.resources<8.0.0 where the byte object was only decoded as a string upon serialization.

Is the intention of elements annotated now with [fhir_core.types.Base64BinaryType](https://github.com/nazrulworld/fhir-core/blob/0f09ff8a6a99553838003a706dcc01187d9099ff/fhir_core/types.py#L984) be expected to already be a base64 encoded bytes object or a byte object which will be converted as such?

### What I Did

```python
import base64

from fhir.resources.attachment import Attachment

encoded_hash = base64.b64encode(b"bytedata")
att = Attachment(hash=encoded_hash)
assert encoded_hash == att.hash
# encoded_hash=b'Ynl0ZWRhdGE=' != att.hash=b'bytedata'
```

Best,
Adam

**Comment by nazrulworld** [comment]
@adamvonpaternos thanks a lot for your input.

Actually `Base64BinaryType` is based on https://docs.pydantic.dev/2.3/usage/types/encoded/#base64-encoding-support 
https://docs.pydantic.dev/latest/api/types/#pydantic.types.Base64Bytes

This field expects the already base64 encoded bytes or str. So if I take your example

```
import base64

from fhir.resources.attachment import Attachment

encoded_hash = base64.b64encode(b"bytedata")
att = Attachment(hash=encoded_hash)
assert b"bytedata" == att.hash
assert encoded_hash == att. model_dump()["hash"].strip()
```

**Comment by adamvonpaternos** [comment]
Is it intended for the instantiated field value of the model to be the base64 decoded byte object? I would expect the hash to be equivalent to the value passed into the field, as well as, not adding a line-feed on serialization. Is this not new behavior seen from 7.0.1 to 8.x?

**Comment by nazrulworld** [comment]
> Is it intended for the instantiated field value of the model to be the base64 decoded byte object?

As I said this behavior inherits from Pydantic v2.

**Comment by adamvonpaternos** [comment]
Thanks. 
> But one problem I can see that it adds extra "\n" during serialization, which I cannot figure out yet about how should solve.

No elegant solution besides creating a custom encoder. However, this should be solved in an upcoming release of Pydantic https://github.com/pydantic/pydantic/pull/10486
