### ISSUE TITLE
Not required property becomes mandatory

### ISSUE THREAD

**Issue by Primetalk** [nazrulworld/fhir.resources#18]
* fhir.resources version: 5.1.1
* Python version: 3.7.5
* Operating System: linux

### Description

Validating claim without `focal`.

It's mandatory in Python: https://github.com/nazrulworld/fhir.resources/blob/5.1.1/fhir/resources/claim.py#L671

```python
("focal", "focal", bool, "boolean", False, None, True)
```
(Where the last `True` is for `not_optional` or mandatory/required as far as I could see.)

(BTW, the same is true for Golang - https://github.com/samply/golang-fhir-models/blob/c26453f28c9f71b1e4e6870ecd633d38b665f005/fhir-models/fhir/claim.go#L116)

In the json schema this field is not required:
```json
    "Claim_Insurance": {


      "properties": {
   

        "focal": {
          "description": "A flag to indicate that this Coverage is to be used for adjudication of this claim when set to true.",
          "$ref": "#/definitions/boolean"
        },
        "_focal": {
          "description": "Extensions for focal",
          "$ref": "#/definitions/Element"
        },
      

        "coverage": {
          "description": "Reference to the insurance card level information contained in the Coverage resource. The coverage issuing insurer will use these details to locate the patient\u0027s actual coverage within the insurer\u0027s information system.",
          "$ref": "#/definitions/Reference"
        }


      },
      "additionalProperties": false,
      "required": [
        "coverage"
      ]
    },
```
### What I Did

```python
    with open("claim.json") as claim_file:
        claim_json = json.load(claim_file)
        claim = Claim(claim_json)
        return claim
```

**Comment by nazrulworld** [comment]
@Primetalk thanks a lot for having this issue.
After this issue, I looked at official FHIR doc here https://www.hl7.org/fhir/claim-definitions.html#Claim.insurance.focal
and found it is mandatory!  `Cardinality | 1..1`
All resources are created here based on FHIR Structure definition, not by following JSON schema. 

I fully agree about this contradictory situation, do you have any link for your provided schema? after then maybe we will post this issue at the official FHIR forum.

**Comment by Primetalk** [comment]
@nazrulworld very interesting.

The JSON schema was obtained from https://www.hl7.org/fhir/fhir.schema.json.zip which is mentioned on the page https://www.hl7.org/fhir/downloads.html.

Do you think there is a mismatch between FHIR Structure definition and JSON schema?

**Comment by nazrulworld** [comment]
I see it's a mismatch situation, we could post https://chat.fhir.org/login/ here.

**Comment by Primetalk** [comment]
Created a topic https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Mandatory.2Foptional.20fields.20inconsistency.20(docs.2Fjson.20schema)
