### ISSUE TITLE
STU3 support missing in pypy version.

### ISSUE THREAD

**Issue by RockHoward** [nazrulworld/fhir.resources#2]
* fhir.resources version: STU3
* Python version: 2.7
* Operating System: *nix

### Description

STU3 code not included in pypy version.

### What I Did

I used 'pip install' to install this package expecting to be able to use the code to support STU3 and R4 projects. However I discovered that the STU3 code was missing.

**Comment by RockHoward** [comment]
I see now that STU3 was not in 4.0.0 which is the default pypy package at the moment. Please treat this issue as I reminder to upgrade the default pypy version soon.

**Comment by nazrulworld** [comment]
@RockHoward  thanks for your interest.

> I see now that STU3 was not in 4.0.0 which is the default pypy package at the moment. Please treat this issue as a reminder to upgrade the default pypy version soon.

**Actually multi versions support start from fhir.resources 5.x.x** which is currently in beta https://pypi.org/project/fhir.resources/5.0.0b2/ , will release stable version soon  after some testing. You are welcome to use the beta release.

**Comment by RockHoward** [comment]
I am getting very close to pushing a project that uses the DSTU2 support into production. It would be great if the 5.x.x version made it into PyPI soon.

**Comment by nazrulworld** [comment]
@RockHoward stable version released!

**Comment by RockHoward** [comment]
Thanks a bunch! Perfect timing.
