### ISSUE TITLE
Create remaning DSTU2 FHIR resources.

### ISSUE THREAD

**Issue by nazrulworld** [nazrulworld/fhir.resources#21]
#19 
# Description
We have yet many DSTU2 FHIR resources to be created, here the list.

- [x]  [dataelement.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/dataelement.py)
- [x]  [detectedissue.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/detectedissue.py)
- [x]  [devicecomponent.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/devicecomponent.py)
- [x]  [devicemetric.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/devicemetric.py)
- [x]  [deviceuserequest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/deviceuserequest.py)
- [x]  [deviceusestatement.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/deviceusestatement.py)
- [x]  [diagnosticorder.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/diagnosticorder.py)
- [x]  [documentmanifest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/documentmanifest.py)
- [x]  [documentreference.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/documentreference.py)
- [x]  [elementdefinition.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/elementdefinition.py)
- [x]  [eligibilityrequest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/eligibilityrequest.py)
- [x]  [eligibilityresponse.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/eligibilityresponse.py)
- [x]  [enrollmentrequest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/enrollmentrequest.py)
- [x]  [enrollmentresponse.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/enrollmentresponse.py)
- [x]  [episodeofcare.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/episodeofcare.py)
- [x]  [explanationofbenefit.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/explanationofbenefit.py)
- [x]  [familymemberhistory.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/familymemberhistory.py)
- [x]  [healthcareservice.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/healthcareservice.py)
- [x]  [imagingobjectselection.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/imagingobjectselection.py)
- [x]  [imagingstudy.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/imagingstudy.py)
- [x]  [immunizationrecommendation.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/immunizationrecommendation.py)
- [x]  [implementationguide.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/implementationguide.py)
- [x]  [list.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/list.py)
- [x]  [medicationdispense.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/medicationdispense.py)
- [x]  [medicationorder.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/medicationorder.py)
- [x]  [messageheader.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/messageheader.py)
- [x]  [namingsystem.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/namingsystem.py)
- [x]  [nutritionorder.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/nutritionorder.py)
- [x]  [operationdefinition.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/operationdefinition.py)
- [x]  [order.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/order.py)
- [x]  [orderresponse.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/orderresponse.py)
- [x]  [parameters.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/parameters.py)
- [x]  [paymentnotice.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/paymentnotice.py)
- [x]  [paymentreconciliation.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/paymentreconciliation.py)
- [x]  [processrequest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/processrequest.py)
- [x]  [processresponse.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/processresponse.py)
- [x]  [provenance.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/provenance.py)
- [x]  [questionnaire.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/questionnaire.py)
- [x]  [questionnaireresponse.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/questionnaireresponse.py)
- [x]  [referralrequest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/referralrequest.py)
- [x]  [riskassessment.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/riskassessment.py)
- [x]  [searchparameter.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/searchparameter.py)
- [x]  [specimen.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/specimen.py)
- [x]  [structuredefinition.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/structuredefinition.py)
- [x]  [subscription.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/subscription.py)
- [x]  [substance.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/substance.py)
- [x]  [supplydelivery.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/supplydelivery.py)
- [x]  [supplyrequest.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/supplyrequest.py)
- [x]  [testscript.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/testscript.py)
- [x]  [visionprescription.py](https://github.com/nazrulworld/fhir.resources/blob/5.X.X/fhir/resources/DSTU2/visionprescription.py)

**Comment by mmabey** [comment]
Hey @nazrulworld, just wanted to give you a quick update on this. I am spending time manually creating these resources. There is a chance some of my teammates will also make some contributions too. My management wants to do an internal review before I open any PRs just to make sure everything we're contributing is appropriate. I will try to periodically submit at least partial PRs so you don't have to review everything all in one go.

**Comment by nazrulworld** [comment]
Thank you so much.

**Comment by ItayGoren** [comment]
Can you please describe shortly how we can help?
Are the resources created manually? What is the convention for names and inner-type names?
Are all the basic types implemented? Such as `Timing` and `Date`

**Comment by nazrulworld** [comment]
@ItayGoren if you look at top of the description, any unchecked resources are yet to be done. 
//_Are all the basic types implemented?_// yes

**Comment by mmabey** [comment]
@nazrulworld I was able to spend time on this again this week. I have completed imagingstudy through medicationorder. I can submit a PR soon so you have those resources, but I should be able to continue spending time on more resources this week. I'll try to keep you up to date.

**Comment by nazrulworld** [comment]
@mmabey good hear 👍

**Comment by nazrulworld** [comment]
@mmabey will you have some time to add more missing resources? Other than maybe I will create some as much as possible and before the new year, we may release the final/stable version (even some DSTU2 resources are remaining)

**Comment by mmabey** [comment]
@nazrulworld Probably not anytime soon, sorry.

**Comment by iatechicken** [comment]
I can spend some time on this over the weekend. These are the same DSTU2 resources that I was working on right?

**Comment by nazrulworld** [comment]
@iatechicken yes
