### ISSUE TITLE
Version 5 method `__eq__`

### ISSUE THREAD

**Issue by ItayGoren** [nazrulworld/fhir.resources#27]
* fhir.resources version: 5
* Python version: 3.8
* Operating System: mac

### Description

As far as I can see, there is no method `__eq__` implemented. Am I missing something? Is it supposed to be added in the future?
Thanks

**Comment by nazrulworld** [comment]
@ItayGoren you are fully right `__eq__` is not implemented in version 5.x.x.
Thanks a lot for raising this issue, as we are too much focused on releasing 6.x.x, right now, so might not possible to look at this issue. But in the future, of course, it could be done.
Also in the meanwhile, any contribution is welcomed 👍 regarding this issue.
