### ISSUE TITLE
`construct_fhir_element` change the given dict

### ISSUE THREAD

**Issue by ItayGoren** [nazrulworld/fhir.resources#28]
* fhir.resources version: 6
* Python version: 3.8
* Operating System: mac

### Description
Running the following code:
```python
from fhir.resources import construct_fhir_element
d = {'resourceType': 'Patient', 'contained':[{'resourceType': 'Patient'}]}
construct_fhir_element('Patient', d)
```
end up changing the value of `d` to `{'resourceType': 'Patient', 'contained': [{}]}`

I would expect it to not change the given object. Moreover, because it doesn't delete `resourceType` from the outter dictionary, I assume this behavior is not expected.
Is it on purpose?
Thanks,
Itay

**Comment by nazrulworld** [comment]
@ItayGoren thank you much for your collaborating 👍
