### ISSUE TITLE
DSTU2 Specimen resource has invalid fields

### ISSUE THREAD

**Issue by ItayGoren** [nazrulworld/fhir.resources#37]
* fhir.resources version: 6.0.0
* Python version: 3.8
* Operating System: MacOS

### Description

While writing tests I found a bug in `Specimen` resource. It looks like his backbone elements are not defined correctly. I'm not sure what I am missing.
A result for example:
```
E   pydantic.error_wrappers.ValidationError: 3 validation errors for Specimen                           
E   collection                                                                                                                                                                                                  
E      (type=value_error)                                                                               
E   treatment -> 0                                                                                                                                                                                              
E      (type=value_error)                                                                               
E   container -> 0                                                                                      
E      (type=value_error)   
```
You can run the tests in the following branch:
https://github.com/ItayGoren/fhir.resources/tree/bug-with-specimen

Thanks

**Comment by nazrulworld** [comment]
@ItayGoren I think it's not a bug inside the `Specimen ` resource rather than a problem in deeper. I can generate this by using  https://www.hl7.org/fhir/DSTU2/uslab/spec-uslab-example1.json this example.

Currently, there is no support for [fhir comment ](http://www.healthintersections.com.au/?p=2569), I believe it's because of that. I have a plan to work on it.

**Comment by nazrulworld** [comment]
Ok @ItayGoren finally! the problem is revealed https://github.com/ItayGoren/fhir.resources/blob/bug-with-specimen/fhir/resources/DSTU2/specimen.py#L140 you see there `resource_type` is missing!
I am fixing it.
