### ISSUE TITLE
Parse to XML

### ISSUE THREAD

**Issue by jxtiben** [nazrulworld/fhir.resources#4]
* fhir.resources version: DSTU2
* Python version: Python 3.7
* Operating System: Linux

### Description

I'm implementing FHIR, version DSTU2 works perfectly but I'd like to know if there is any way to parse the resources (MessageHeader, Patient, ...) to XML format?

### What I Did

According to the documentation "binary.as_json()" is the way to convert to Json format but I'm not sure if there is a function to convert to XML

**Comment by nazrulworld** [comment]
Hi @jxtiben 

Thanks for your interest. Actually, there is no XML format implementation.
I found some online and offline tools, from where you can convert JSON to XML resources.

The process would be like, generate json file or string using this model and manually convert them (maybe there could be a better way to do that. )

1. https://fhir-formats.github.io/
2. https://github.com/kwboone/FHIR-JSON-to-XML-Converter/

**Comment by jxtiben** [comment]
Ok, I got it. I will check them. Thanks
