### ISSUE TITLE
Contained Resources 

### ISSUE THREAD

**Issue by dragos-dobre** [nazrulworld/fhir.resources#45]
### Description

I need to implement the Contained Resources (https://www.hl7.org/fhir/references.html#contained) and to send the reference resources inside the referred resource. In my case, I need to send a Claim with all reference resources:  Patient, Condition, etc. 

Is this feature available in fhir.resources?

Thanks.

**Comment by nazrulworld** [comment]
Yes, should be possible.
If you face any problem let us know.
