### ISSUE TITLE
Help on converting XML to FHIR format

### ISSUE THREAD

**Issue by challavamsi** [nazrulworld/fhir.resources#51]
* fhir.resources version:
* Python version:
* Operating System:

### Description
Hi I am a newbie to FHIR data formats. This might be a dumb questions as well,  is there any easy way to convert bunch of XML's to FHIR format? any suggestions on  blog/tutorials for reference?

Any help is appreciated!!
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Healthedata1** [comment]
convert bunch of XML's to FHIR format?  I  think you mean xml to json.  One way is to use the convert operation on a reference server:  https://build.fhir.org/resource-operation-convert.html 

There are also tools that do this too

**Comment by nazrulworld** [comment]
I think that kind supporting is coming soon. https://github.com/nazrulworld/fhir.resources/tree/yaml-xml-support [working in progress]
