### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by ItayGoren** [nazrulworld/fhir.resources#53]
Hey,
When would the new version be released with the changes in the change log?
Thanks

**Comment by nazrulworld** [comment]
I was thinking to add support to some features related to https://github.com/nazrulworld/fhir.resources/issues/47, but honestly speaking, for me, cannot manage time!
So I think a new release should be soon as possible.

**Comment by nazrulworld** [comment]
I am sorry to see that you are not notified, I should notify you.
 https://pypi.org/project/fhir.resources/6.1.0/
