### ISSUE TITLE
Any resource: "id" element fails validation with underscore in value

### ISSUE THREAD

**Issue by sbwhitney** [nazrulworld/fhir.resources#55]
* fhir.resources version: 6.1.0
* Python version: Python 3.8.6
* Operating System: Linux

### Description

If resource.id element has an underscore, validation fails

### What I Did

```
resource = {'resourceType': 'Patient', 'id': 'abc_1234'}
Patient(**resource)
```
pydantic.error_wrappers.ValidationError: 1 validation error for Patient
id
  string does not match regex "^[A-Za-z0-9\-.]+$" (type=value_error.str.regex; pattern=^[A-Za-z0-9\-.]+$)

**Comment by sbwhitney** [comment]
@nazrulworld I can make a PR request to update this line:

https://github.com/nazrulworld/fhir.resources/blob/9e81ed05607389158f5fc997d9a3ab19bd18e6e1/fhir/resources/fhirtypes.py#L136

But would you want to update for all FHIR versions? 

`^[A-Za-z0-9\-_.]+$ ` would be the new regex

**Comment by nazrulworld** [comment]
First of all @sbwhitney thanks a lot for this issue.
If you look at FHIR specification https://www.hl7.org/fhir/datatypes.html#id by default (_) is not allowed. So the default behavior is  `regex = re.compile(r"^[A-Za-z0-9\-.]+$")`  (should be if your system communicate to other system)
But it is possible to override this behavior. https://github.com/nazrulworld/fhir.resources#resourceid-aka-fhirtypesid-constraint-extensibility
```
>>> from fhir.resources.fhirtypes import Id
>>> Id.configure_constraints(regex=re.compile(r"^[A-Za-z0-9\-_.]+$"))
```

**For PR.**
1. fork this repo
2. Make PR 
Hopefully should work, if still, you are facing a problem let me know.

**Comment by sbwhitney** [comment]
Thanks for the info @nazrulworld. Much appreciated. No PR necessary as underscore (_) is disallowed.
