### ISSUE TITLE
How to build a Model in Django using this Package 

### ISSUE THREAD

**Issue by ShaikhSuf** [nazrulworld/fhir.resources#59]
* fhir.resources version: 6.1
* Python version: 3.8
* Operating System: iOS

### Description

There's no issue as such. I'm trying to create a Django model using this project, for example, the patient resource. 

Does this package support creation of a model?

**Comment by nazrulworld** [comment]
Most probably you cannot just represent directly Patient Resource as DJ Model, instead, you can create a Patient model which could have field name `resource` and type is JSON so this field will contain the whole resource.

But I think there could be another better solution.

**Comment by ShaikhSuf** [comment]
My goal is to mimic the resource models in Python to be in sync with resources. 

Thanks for the suggestion, though.

**Comment by Bijitakc** [comment]
@ShaikhSuf Did you find out a way to represent the resources in django models?
