### ISSUE TITLE
ExplanationOfBenefit

### ISSUE THREAD

**Issue by nishank974** [nazrulworld/fhir.resources#61]
* fhir.resources version: 6.1.0
* Python version: 3.8.3
* Operating System: MacOS Catalina

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I have a record of ExplanationOfBenefit in json format.
When I pass it to fhir.resources.ExplanationOfBenefit it get the following error.

`
ValidationError: 2 validation errors for ExplanationOfBenefit
__root__ -> created
  field required (type=value_error.missing)
__root__ -> outcome
  field required (type=value_error.missing)
`

### What I Did

`
record = records[5945]
from fhir.resources.explanationofbenefit import ExplanationOfBenefit
Eob = ExplanationOfBenefit(**record)
`

**How can I know what values are missing and is there a way to print the missing values**

**Comment by nazrulworld** [comment]
I see from your error message that 
`ExplanationOfBenefit. created `and ` ExplanationOfBenefit. outcome` values are missing, those are required http://www.hl7.org/fhir/explanationofbenefit.html
as per specification.
