### ISSUE TITLE
contact.telecom.extension.valueUrl does not validate phone number values

### ISSUE THREAD

**Issue by lee-hyunkyu** [nazrulworld/fhir.resources#62]
* fhir.resources version: 6.1.0
* Python version: 3.7
* Operating System: Ubuntu 18.04

### Description

I'm trying to construct a `Patient` resource after fetching it via a FHIR call. 

### What I Did
I fetched some data and tried to construct it using the `Patient` model class. 

The contact field for the resulting patient information was 

```js
"contact": [
    {
        "relationship": [{ /* a relationship object */}],
        "name": { /* a name object */ },
        "telecom": [{
            "extension": [{
                "valueUrl": "(123)123-1234",
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-TEL-address"
            }],
            /* rest of the telecom object*/
        }]
    }],
```

```
contact -> 0 -> telecom -> 0 -> extension -> 0 -> valueUrl
invalid or missing URL scheme (type=value_error.url.scheme)
```

The [url rfc](https://tools.ietf.org/html/rfc1738) defines that parenthesis are not valid so the sender seems to be at fault. Is there any way for me to continue to use the library to construct this `Patient` resource and specifically ignore validating this field?

**Comment by nazrulworld** [comment]
One solution could be if possible change ``valueUrl `` to ``valueString``.  But it is not possible to turn that validation off.

**Comment by lee-hyunkyu** [comment]
Unfortunately that's not possible. Going to close the issue since we found a workaround
