### ISSUE TITLE
treating empty lists ('[]') as None

### ISSUE THREAD

**Issue by Healthedata1** [nazrulworld/fhir.resources#73]
* fhir.resources version:  R4
* Python version: 3.7.3
* Operating System: Mac OS

### Description

I am creating a FHIR object using the models and a spreadsheet as a source
When there is repeating element and their is no data in the source, my code creates an empty list.
This empty list is preserved unlike when the element is None.  I think when an element is evaluated to these Falsy types listed below I think it should behave the same ... namely the element value should be `None`. Note that in FHIR "when present, elements *cannot* be empty - they **SHALL**  have a value attribute, child elements, or extensions".

1. None
1. [] - an empty list
1. {} - an empty dict
1. () - an empty tuple
1. '' - an empty str
1. b'' - an empty bytes
1. set() - an empty set. 

### What I Did
~~~python
cs = construct_fhir_element('CapabilityStatement',dict(
id = meta.id,
url = f'{canon}CapabilityStatement/{meta.id}',
version = meta.version,
# more elements
instantiates = [i for i in meta.instantiates.split(',') if i],  #<<<< this evaluates to '[]'  instead of None 
))
~~~

Note that I can code around this but I think this should be the default behavior of the classes as a convienence.

**Comment by Healthedata1** [comment]
never mind :-)

**Comment by vadi2** [comment]
What solution did you end up going with? Not creating the list to begin with?
