### ISSUE TITLE
Remove "tests" from installed package

### ISSUE THREAD

**Issue by ItayGoren** [nazrulworld/fhir.resources#75]
* fhir.resources version: latest
* Python version: 3.8
* Operating System: everything

### Description

When installing the package, the "tests" folder is being installed which takes 10MB from the system. It might not sound a lot but when using AWS serverless applications, you have 250MB storage and 10MB can be critical.
The problem is in the project "setup.py" by using "find_packages" which finds the tests directory.
It needs to be filtered out.

### What I Did

Opened a ticket 😃

**Comment by nazrulworld** [comment]
Thanks a lot, I will take care of it
