### ISSUE TITLE
Contribution Guidelines Appear to Be Out of Date

### ISSUE THREAD

**Issue by dixonwhitmire** [nazrulworld/fhir.resources#79]
* fhir.resources version: 6.2.0,b3
* Python version: 3.9.7
* Operating System: OS X (11.5.2)

### Description

The Contribution guidelines appear to be out of date, given the current state of the project. For example:

* pipenv is referenced, but dependencies are managed using setup.py and possibly make
* testing guidelines indicate that python 2.7 is supported, which isn't compatible with pydantic

### What I Did

My team is starting to use fhir.resources in a new project. We are happy to help revise the contributing documentation, and align the "build"/setup process with the maintainer's intent. In order to proceed, it would be helpful to know:

* Supported Python versions are: 3.6, 3.7, 3.8, and 3.9 appropriate?  These are the versions Pydantic supports.
* Dependency management - pipenv , setup.py, or possibly setup.cfg with a pyproject.toml?
* Would you still like to use make as a front-end for local development and CI/CD?
* Can we use GitHub actions to target the supported Python versions?

Finally, thank you very much for this library! It's great to have a Pydantic based FHIR library available for use. If we can assist with these changes, please let us know.

**Comment by nazrulworld** [comment]
@dixonwhitmire First of thanks a lot for your willingness to contribute. 
1. pipenv is no longer dependent on development.
2. yes 3.6, 3.7, 3.8, and 3.9  versions are supported.
You are welcome to come with any improvements.
Feel free to make any PR

**Comment by dixonwhitmire** [comment]
Hi @nazrulworld thank you for the clarification! We will open a PR if necessary and as time allows. Thanks!
