### ISSUE TITLE
How to use this as a FHIR Server

### ISSUE THREAD

**Issue by PeteW** [nazrulworld/fhir.resources#9]
* fhir.resources version: 5.1.0
* Python version: 3.7.6
* Operating System: Linux

### Description
Disclaimer I am getting started with FHIR.
My high level goal is to implement some basic FHIR resources on a flask API server. 
Expose some FHIR search capabilities. Run some basic queries on a backend store, populate FHIR resource objects, return these resources in FHIR-compliant JSON structure response.

### What I Did

```
>>> from fhir.resources.fhirelementfactory import FHIRElementFactory
>>> json_dict = {"resourceType": "Organization", "id": "foo", "active": True, "name": "acme", "address": [{"country": "us"}]}
>>> org = FHIRElementFactory.instantiate('Organization', json_dict)
>>> org.address[0].country == "Swizterland"
False
>>> org.address[0].country == "us"
True
>>> org.as_json()['active'] is True
True
>>> repr(org)
'<fhir.resources.organization.Organization object at 0x02DF5250>'
>>> org.as_json()
{'id': 'foo', 'active': True, 'address': [{'country': 'us'}], 'name': 'acme', 'resourceType': 'Organization'}
```
All of this is fine but that JSON is not a true FHIR resource response as I understand it to be. For example it is missing things like `resourcetype`

Is my understanding of the above correct? Is there a better way? Am I getting too old for programming and need to check myself into a retirement community?

**Comment by nazrulworld** [comment]
> JSON is not a true FHIR resource response as I understand it to be. For example it is missing things like resourcetype

Can you please more elaborate? what you mean JSON here and you mention resourceType is missing.

**Comment by PeteW** [comment]
Thanks for writing back. I've gotten much smarter since I wrote this. I took the JSON output produced by this library, I ran it through a comprehensive FHIR validator, worked on the feedback and was able to produce what I needed. This works really well once you get the hang of it.
